language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo test
  - rustup component add rustfmt
  - cargo fmt --version
  - cargo fmt --all -- --check
